### ISSUE TITLE
[Feature] `d_features` referring others values

### ISSUE THREAD

**Issue by markoshorro** [UDC-GAC/MARTA#11]
Having:

```
foo:
   evaluate: True
   type: "numeric"
   value: [0,1,2]
```

It could be good to have something like:

```
bar:
   evaluate: True
   type: "dependent"
   value: foo * 2
```

So the values of `bar` would be `[0,2,4]`.
