### ISSUE TITLE
[Enhacenment] Simplify `d_feature` definition

### ISSUE THREAD

**Issue by markoshorro** [UDC-GAC/MARTA#12]
Right now, we have different fields for each `d_feature` (default values):

```
foo:
    evaluate: True
    type: "static" | "dynamic" | "dependent"
    val_type: "numeric"
    values: None
    restrict: None
```

I think we could get rid of `evaluate` and `val_type`, they are confusing to me right now. If you want to evaluate something, just put it, otherwise, comment it or just remove it. `val_type` is something you can get dynamically, there is no need to specify it explicitly. This way we only leave the important ones: `values` (plural), `restrict` (single expression at the moment), and `type`.

Probably `type` is also confusing, you could understand data type. Probably `expr_type` is more accurate, having as aliases `etype` and just `type`.

## Default values:

  * `expr_type`: "static"
  * `values`: None
  * `restrict`: None
