### ISSUE TITLE
[Feature] Conditional `d_features`

### ISSUE THREAD

**Issue by markoshorro** [UDC-GAC/MARTA#7]
Maybe we want to limit certain values to the value of other variables, e.g.:

```
d_features:
    foo:
        evaluate: True
        type: "string"
        value: [0,2]
    bar:
        evaluate: True
        type: "string"
        value: [0,1]
```

For the sake of the argument, imagine when `foo` is lower than `2`, `bar` variable has no effect and, therefore, we do not want to generate the combination with the `bar` values. So the list of combinations would be:

  * `[foo: 0]` , `[foo: 2, bar: 0]`, `[foo: 2, bar: 1]`

We could write that description as:

```
    bar:
        evaluate: True
        type: "string"
        value: [0,1]
        restrict: "foo > 1"
```
